
import fs from 'fs';
import webpack from 'webpack';
import devConfig from '../../webpack.dev';
import { version } from '../../package.json';
import WebpackDevServer from 'webpack-dev-server';

try {
    console.log('Generating version.ts');
    const versionFileData = `// generated by serveWeb or buildWeb script\nexport const version = '${version}';\n`;
    fs.writeFileSync('version.ts', versionFileData, { flag: 'w' });

    const webpackCompiler = webpack(devConfig);

    const devServerOptions = { ...devConfig.devServer };
    const server = new WebpackDevServer(devServerOptions, webpackCompiler);

    server.startCallback((error) => {
        if (error) {
            console.error('Error when starting the server', error);
        } else {
            console.log('Successfully started server on http://localhost:8080');
        }
    });

} catch (error) {
    console.error('Error when serving web', error);
}

export default null;
